### ISSUE TITLE
How do I specify header parameters?

### ISSUE THREAD

**Issue by fatso83** [sidorares/node-wrk#5]
We have urls with some security related restrictions where we need to specify stuff like API keys and Cookies when testing the throughput. How can I specify this with `node-wrk`?

**Comment by sidorares** [comment]
You can add headers with `--header` switch but that's not supported yet by this wrapper

**Comment by fatso83** [comment]
OK, I or @tommhuth might come up with a PR for that.

**Comment by sidorares** [comment]
that would be great @fatso83 

relevant parts in the code: https://github.com/wg/wrk/blob/03dc368674402f4b26a862f941f29887d06fd564/src/wrk.c#L51
and https://github.com/sidorares/node-wrk/blob/d889a71353f11ff90eaa86dc9043c318bad14284/index.js#L8-L20

**Comment by sidorares** [comment]
and for super powers - api to inject lua script ( `-s` )

https://github.com/wg/wrk/issues/48
https://github.com/timotta/wrk-scripts

**Comment by tommhuth** [comment]
Looks like I've got header support up and running on my fork. Created a pull request, @sidorares.
